import {SObject, ChildRecord} from '../../utils/sobject.model';
import {Product, ProductFactory} from '../product/product.model';
import {Account, AccountLocation, AccountLocationFactory, AccountFactory} from '../account/account.model';
import {Category, CategoryFactory} from '../category/category.model';
import {Cart, CartFactory} from '../cart/cart.model';
import {Order, OrderFactory} from './order.model';
import {PriceList, PriceListFactory} from '../price-list/price-list.model';
import {PriceListItem, PriceListItemFactory} from '../price-list/price-list-item.model';
import {OrderProductAttributeValue, OrderProductAttributeValueFactory} from '../product-attribute/product-attribute-value.model';

export interface OrderLineItem extends SObject{
    Apttus_Config2__AdjustedPrice__c:    number;
    Apttus_Config2__AdjustmentAmount__c: number;
    Apttus_Config2__AdjustmentType__c:   string;
    Apttus_Config2__AutoRenew__c:    boolean;
    Apttus_Config2__AutoRenewalTerm__c:  number;
    Apttus_Config2__AutoRenewalType__c:  string;
    Apttus_Config2__BaseCost__c: number;
    Apttus_Config2__BaseCostOverride__c: number;
    Apttus_Config2__BaseExtendedCost__c: number;
    Apttus_Config2__BaseExtendedPrice__c:    number;
    Apttus_Config2__BasePrice__c:    number;
    Apttus_Config2__BasePriceOverride__c:    number;
    Apttus_Config2__BasePriceMethod__c:  string;
    Apttus_Config2__BaseProductId__c: string;
    Apttus_Config2__BaseProductId__r: Product;
    Apttus_Config2__BillingFrequency__c: string; 
    Apttus_Config2__BillingRule__c:  string;
    Apttus_Config2__BillToAccountId__r:  Account;
    Apttus_Config2__BillToAccountId__c:  string;
    Apttus_Config2__cancelledDate__c:    Date;
    Apttus_Config2__classificationId__r: Category;
    Apttus_Config2__classificationId__c: string;
    Apttus_Config2__classificationHierarchy__c:  string;
    Apttus_Config2__chargeType__c:   string;
    Apttus_Config2__comments__c: string;
    Apttus_Config2__commitmentQuantity__c:   number;
    Apttus_Config2__configurationId__r:  Cart;
    Apttus_Config2__configurationId__c: string;
    Apttus_Config2__contractNumbers__c:  string;
    Apttus_Config2__cost__c: number;
    Apttus_Config2__couponCode__c:   string;
    Apttus_Config2__DeltaPrice__c:   number;
    Apttus_Config2__DeltaQuantity__c:    number;
    Apttus_Config2__Description__c:  string;
    Apttus_Config2__EndDate__c:  Date;
    Apttus_Config2__ExtendedCost__c: number;
    Apttus_Config2__ExtendedDescription__c:  string;
    Apttus_Config2__ExtendedPrice__c:    number;
    Apttus_Config2__ExtendedQuantity__c: number;
    Apttus_Config2__FlatOptionPrice__c:  number;
    Apttus_Config2__FulfilledQuantity__c:   number;
    Apttus_Config2__GroupAdjustmentPercent__c: number;
    Apttus_Config2__Guidance__c: string;
    Apttus_Config2__HasAttributes__c:    boolean;
    Apttus_Config2__HasIncentives__c:    boolean;
    Apttus_Config2__HasOptions__c:   boolean;
    Apttus_Config2__HideInvoiceDisplay__c:   boolean;
    Apttus_Config2__ImpactARR__c:    number;
    Apttus_Config2__ImpactMRR__c:    number;
    Apttus_Config2__ImpactTCV__c:    number;
    Apttus_Config2__IncentiveAdjustmentAmount__c:    number;
    Apttus_Config2__IncentiveCode__c:    string;
    Apttus_Config2__IncentiveExtendedPrice__c:   number;
    Apttus_Config2__IncentiveType__c:    string;
    Apttus_Config2__IsAssetPricing__c:   boolean;
    Apttus_Config2__IsCustomPricing__c:  boolean;
    Apttus_Config2__IsOptionRollupLine__c:   boolean;
    Apttus_Config2__IsPrimaryLine__c:    boolean;
    Apttus_Config2__IsPrimaryRampLine__c:    boolean;
    Apttus_Config2__IsUsageTierModifiable__c:    boolean;
    Apttus_Config2__ItemSequence__c: number;
    Apttus_Config2__LineNumber__c:   number;
    Apttus_Config2__LineStatus__c:   string;
    Apttus_Config2__LineType__c: string;
    Apttus_Config2__ListPrice__c:    number;
    Apttus_Config2__LocationId__r: AccountLocation;
    Apttus_Config2__MaxUsageQuantity__c: number;
    Apttus_Config2__MinUsageQuantity__c: number;
    Apttus_Config2__NetAdjustmentPercent__c: number;
    Apttus_Config2__NetPrice__c: number;
    Apttus_Config2__NetUnitPrice__c: number;
    Apttus_Config2__OptionId__r: Product;
    Apttus_Config2__OptionCost__c:   number;
    Apttus_Config2__OptionPrice__c:  number;
    Apttus_Config2__OrderId__c: string;
    Apttus_Config2__OrderARR__c: number;
    Apttus_Config2__OrderMRR__c: number;
    Apttus_Config2__OrderTCV__c: number;
    Apttus_Config2__ParentBundleNumber__c:   number;
    Apttus_Config2__PriceAdjustment__c:  number;
    Apttus_Config2__PriceAdjustmentAmount__c:    number;
    Apttus_Config2__PriceAdjustmentType__c:  string;
    Apttus_Config2__PriceGroup__c:   string;
    Apttus_Config2__PriceIncludedInBundle__c:    boolean;
    Apttus_Config2__PriceListId__r: PriceList;
    Apttus_Config2__PriceListItemId__r: PriceListItem;
    Apttus_Config2__PriceMethod__c:  string;
    Apttus_Config2__PriceType__c:    string;
    Apttus_Config2__PricingDate__c:  Date;
    Apttus_Config2__Frequency__c:    string;
    Apttus_Config2__Term__c: number;
    Apttus_Config2__PriceUom__c: string;
    Apttus_Config2__PrimaryLineNumber__c:    number;
    Apttus_Config2__ProductId__r: Product;
    Apttus_Config2__ProductId__c: string;
    Apttus_Config2__Uom__c:  string;
    Apttus_Config2__Quantity__c: number;
    Apttus_Config2__ActivatedDate__c:    Date;
    Apttus_Config2__ReadyForBillingDate__c:  Date;
    Apttus_Config2__FulfilledDate__c:    Date;
    Apttus_Config2__ReadyForRevRecDate__c:   Date;
    Apttus_Config2__RebateAmount__c: number;
    Apttus_Config2__RenewalAdjustmentAmount__c:  number;
    Apttus_Config2__RenewalAdjustmentType__c:    string;
    Apttus_Config2__SellingFrequency__c: string;
    Apttus_Config2__SellingTerm__c:  number;
    Apttus_Config2__ShipToAccountId__r: Account;
    Apttus_Config2__StartDate__c:    Date
    Apttus_Config2__Status__c:   string;
    Apttus_Config2__SubType__c:  string;
    Apttus_Config2__Taxable__c:  boolean;
    Apttus_Config2__TaxInclusive__c: boolean;
    Apttus_Config2__Type__c: string;
    Apttus_Config2_DiscountPercent__c:   number;
    Apttus_Config2__AttributeValueId__r: OrderProductAttributeValue;
}

export function OrderLineItemFactory(priceListId: string): OrderLineItem{
    return {
        _type : 'Apttus_Config2__OrderLineItem__c',
        Apttus_Config2__AdjustedPrice__c:    null,
        Apttus_Config2__AdjustmentAmount__c: null,
        Apttus_Config2__AdjustmentType__c:   null,
        Apttus_Config2__AutoRenew__c:    false,
        Apttus_Config2__AutoRenewalTerm__c:  null,
        Apttus_Config2__AutoRenewalType__c:  null,
        Apttus_Config2__BaseCost__c: null,
        Apttus_Config2__BaseCostOverride__c: null,
        Apttus_Config2__BaseExtendedCost__c: null,
        Apttus_Config2__BaseExtendedPrice__c:    null,
        Apttus_Config2__BasePrice__c:    null,
        Apttus_Config2__BasePriceOverride__c:    null,
        Apttus_Config2__BasePriceMethod__c:  null,
        Apttus_Config2__BaseProductId__c: null,
        Apttus_Config2__BaseProductId__r: ProductFactory(priceListId),
        Apttus_Config2__BillingFrequency__c: null, 
        Apttus_Config2__BillingRule__c:  null,
        Apttus_Config2__BillToAccountId__r:  AccountFactory(),
        Apttus_Config2__BillToAccountId__c:  null,
        Apttus_Config2__cancelledDate__c:    null,
        Apttus_Config2__classificationId__r: CategoryFactory(priceListId),
        Apttus_Config2__classificationId__c: null,
        Apttus_Config2__classificationHierarchy__c:  null,
        Apttus_Config2__chargeType__c:   null,
        Apttus_Config2__comments__c: null,
        Apttus_Config2__commitmentQuantity__c:   null,
        Apttus_Config2__configurationId__r:  CartFactory(priceListId),
        Apttus_Config2__configurationId__c: null,
        Apttus_Config2__contractNumbers__c:  null,
        Apttus_Config2__cost__c: null,
        Apttus_Config2__couponCode__c:   null,
        Apttus_Config2__DeltaPrice__c:   null,
        Apttus_Config2__DeltaQuantity__c:    null,
        Apttus_Config2__Description__c:  null,
        Apttus_Config2__EndDate__c:  null,
        Apttus_Config2__ExtendedCost__c: null,
        Apttus_Config2__ExtendedDescription__c:  null,
        Apttus_Config2__ExtendedPrice__c:    null,
        Apttus_Config2__ExtendedQuantity__c: null,
        Apttus_Config2__FlatOptionPrice__c:  null,
        Apttus_Config2__FulfilledQuantity__c:   null,
        Apttus_Config2__GroupAdjustmentPercent__c: null,
        Apttus_Config2__Guidance__c: null,
        Apttus_Config2__HasAttributes__c:    false,
        Apttus_Config2__HasIncentives__c:    false,
        Apttus_Config2__HasOptions__c:   false,
        Apttus_Config2__HideInvoiceDisplay__c:   false,
        Apttus_Config2__ImpactARR__c:    null,
        Apttus_Config2__ImpactMRR__c:    null,
        Apttus_Config2__ImpactTCV__c:    null,
        Apttus_Config2__IncentiveAdjustmentAmount__c:    null,
        Apttus_Config2__IncentiveCode__c:    null,
        Apttus_Config2__IncentiveExtendedPrice__c:   null,
        Apttus_Config2__IncentiveType__c:    null,
        Apttus_Config2__IsAssetPricing__c:   false,
        Apttus_Config2__IsCustomPricing__c:  false,
        Apttus_Config2__IsOptionRollupLine__c:   false,
        Apttus_Config2__IsPrimaryLine__c:    false,
        Apttus_Config2__IsPrimaryRampLine__c:    false,
        Apttus_Config2__IsUsageTierModifiable__c:    false,
        Apttus_Config2__ItemSequence__c: null,
        Apttus_Config2__LineNumber__c:   null,
        Apttus_Config2__LineStatus__c:   null,
        Apttus_Config2__LineType__c: null,
        Apttus_Config2__ListPrice__c:    null,
        Apttus_Config2__LocationId__r: AccountLocationFactory(),
        Apttus_Config2__MaxUsageQuantity__c: null,
        Apttus_Config2__MinUsageQuantity__c: null,
        Apttus_Config2__NetAdjustmentPercent__c: null,
        Apttus_Config2__NetPrice__c: null,
        Apttus_Config2__NetUnitPrice__c: null,
        Apttus_Config2__OptionId__r: ProductFactory(priceListId),
        Apttus_Config2__OptionCost__c:   null,
        Apttus_Config2__OptionPrice__c:  null,
        Apttus_Config2__OrderId__c: null,
        Apttus_Config2__OrderARR__c: null,
        Apttus_Config2__OrderMRR__c: null,
        Apttus_Config2__OrderTCV__c: null,
        Apttus_Config2__ParentBundleNumber__c:   null,
        Apttus_Config2__PriceAdjustment__c:  null,
        Apttus_Config2__PriceAdjustmentAmount__c:    null,
        Apttus_Config2__PriceAdjustmentType__c:  null,
        Apttus_Config2__PriceGroup__c:   null,
        Apttus_Config2__PriceIncludedInBundle__c:    false,
        Apttus_Config2__PriceListId__r: PriceListFactory(),
        Apttus_Config2__PriceListItemId__r: PriceListItemFactory(priceListId),
        Apttus_Config2__PriceMethod__c:  null,
        Apttus_Config2__PriceType__c:    null,
        Apttus_Config2__PricingDate__c:  null,
        Apttus_Config2__Frequency__c:    null,
        Apttus_Config2__Term__c: null,
        Apttus_Config2__PriceUom__c: null,
        Apttus_Config2__PrimaryLineNumber__c:    null,
        Apttus_Config2__ProductId__r: ProductFactory(priceListId),
        Apttus_Config2__Uom__c:  null,
        Apttus_Config2__Quantity__c: null,
        Apttus_Config2__ActivatedDate__c:    null,
        Apttus_Config2__ReadyForBillingDate__c:  null,
        Apttus_Config2__FulfilledDate__c:    null,
        Apttus_Config2__ReadyForRevRecDate__c:   null,
        Apttus_Config2__RebateAmount__c: null,
        Apttus_Config2__RenewalAdjustmentAmount__c:  null,
        Apttus_Config2__RenewalAdjustmentType__c:    null,
        Apttus_Config2__SellingFrequency__c: null,
        Apttus_Config2__SellingTerm__c:  null,
        Apttus_Config2__ShipToAccountId__r: AccountFactory(),
        Apttus_Config2__StartDate__c:    null,
        Apttus_Config2__Status__c:   null,
        Apttus_Config2__SubType__c:  null,
        Apttus_Config2__Taxable__c:  false,
        Apttus_Config2__TaxInclusive__c: false,
        Apttus_Config2__Type__c: null,
        Apttus_Config2_DiscountPercent__c:   null,
        Apttus_Config2__ProductId__c: null,
        Apttus_Config2__AttributeValueId__r: OrderProductAttributeValueFactory()
    } as OrderLineItem;
}