import {SObject, ChildRecord} from '../../utils/sobject.model';
import {Account, AccountFactory} from '../account/account.model';

export interface Quote extends SObject{
	Apttus_QPConfig__ABOType__c:	string;
	Apttus_QPConfig__Accept__c:	string;
	Apttus_Proposal__Account__c:	string;
	Apttus_Proposal__Amount__c:	number;
	Apttus_Proposal__Approval_Stage__c:	string;
	Apttus_QPConfig__AutoActivateOrder__c:	boolean;
	Apttus_QPConfig__AutoCreateBill__c:	boolean;
	Apttus_QPConfig__AutoCreateRevenue__c:	boolean;
	Apttus_QPConfig__BillingPreferenceId__c:	string;
	Apttus_QPConfig__BillToAccountId__c:	string;
	Apttus_QPConfig__BillToAccountId__r:	Account;
	Apttus_QPConfig__configurationFinalizedDate__c:	Date;
	Apttus_QPConfig__configurationSyncDate__c:	Date;
	Apttus_QPConfig__configure__c:	string;
	Apttus_QPAsset__configureWithAssets__c:	string;
	Apttus_QPConfig__configureNG__c:	string;
	Apttus_Proposal__createAgreement__c:	string;
	Apttus_Proposal__Description__c:	string;
	Apttus_Proposal__Discount_Percent__c:	number;
	Apttus_Proposal__ExpectedEndDate__c:	Date;
	Apttus_Proposal__ExpectedStartDate__c:	Date;
	Apttus_Proposal__Generate__c:	string;
	Apttus_Proposal__Grand_Total__c:	number;
	Apttus_Proposal__Internal_Deadline__c:	Date;
	Apttus_QPConfig__IsSystemGenerated__c:	boolean;
	Apttus_QPConfig__IsTaskPending__c:	boolean;
	Apttus_QPConfig__LocationId__c:	string;
	Apttus_Proposal__MakePrimary__c:	string;
	Apttus_Proposal__Net_Amount__c:	number;
	Apttus_Proposal__Opportunity__c:	string;
	Apttus_Proposal__Payment_Term__c:	string;
	Apttus_QPConfig__PaymentTermId__c:	string;
	Apttus_QPConfig__PODate__c:	Date;
	Apttus_QPConfig__PONumber__c:	string;
	Apttus_Proposal__Present__c:	string;
	Apttus_Proposal__Presented_Date__c:	Date;
	Apttus_Proposal__Preview__c:	string;
	Apttus_QPConfig__PriceListId__c:	string;
	Apttus_QPConfig__PricingDate__c:	Date;
	Apttus_Proposal__Primary__c:	boolean;
	Apttus_Proposal__Primary_Contact__c:	string;
	Apttus_Proposal__Proposal_Approval_Date__c:	Date;
	Apttus_Proposal__Proposal_Category__c:	string;
	Apttus_Proposal__Proposal_Expiration_Date__c:	Date;
	Apttus_Proposal__Proposal_Name__c:	string;
	Apttus_QPConfig__ReadyForActivationDate__c:	Date;
	Apttus_QPConfig__ReadyForBillingDate__c:	Date;
	Apttus_QPConfig__ReadyForFulfillmentDate__c:	Date;
	Apttus_QPConfig__ReadyForRevRecDate__c:	Date;
	Apttus_Proposal__ReadyToGenerate__c:	boolean;
	Apttus_Proposal__ReadyToPresent__c:	boolean;
	Apttus_Proposal__Request_Approval__c:	string;
	Apttus_Proposal__RFP_Intake_Date__c:	Date;
	Apttus_Proposal__RFP_Response_Due_Date__c:	Date;
	Apttus_Proposal__RFP_Stage__c:	string;
	Apttus_Proposal__RFP_Value__c:	number;
	Apttus_Proposal__Risk_Factors__c:	string;
	Apttus_Proposal__Sales_Tax_Percent__c:	number;
	Apttus_Proposal__Sales_Tax_Amount__c:	number;
	Apttus_Proposal__SendProposal__c:	string;
	Apttus_Proposal__Shipping_Handling__c:	number;
	Apttus_QPConfig__ShipToAccountId__c:	string;
	Apttus_QPConfig__ShipToAccountId__r:	Account;
	Apttus_Proposal__Special_Terms__c:	string;
	Apttus_Proposal__Strategic_Importance__c:	string;
	Apttus_Proposal__SubmitForApproval__c:	string;
	Apttus_QPConfig__SyncAssetChangesToQuote__c:	boolean;
	Apttus_QPConfig__SyncWithOpportunity__c:	string;
	Apttus_Proposal__Valid_Until_Date__c:	Date;
}

export function QuoteFactory(): Quote{
	return {
		_type : 'Apttus_Proposal__Proposal__c',
		Apttus_QPConfig__ABOType__c:	null,
		Apttus_QPConfig__Accept__c:	null,
		Apttus_Proposal__Account__c:	null,
		Apttus_Proposal__Amount__c:	null,
		Apttus_Proposal__Approval_Stage__c:	null,
		Apttus_QPConfig__AutoActivateOrder__c:	null,
		Apttus_QPConfig__AutoCreateBill__c:	null,
		Apttus_QPConfig__AutoCreateRevenue__c:	null,
		Apttus_QPConfig__BillingPreferenceId__c:	null,
		Apttus_QPConfig__BillToAccountId__c:	null,
		Apttus_QPConfig__configurationFinalizedDate__c:	null,
		Apttus_QPConfig__configurationSyncDate__c:	null,
		Apttus_QPConfig__configure__c:	null,
		Apttus_QPAsset__configureWithAssets__c:	null,
		Apttus_QPConfig__configureNG__c:	null,
		Apttus_Proposal__createAgreement__c:	null,
		Apttus_Proposal__Description__c:	null,
		Apttus_Proposal__Discount_Percent__c:	null,
		Apttus_Proposal__ExpectedEndDate__c:	null,
		Apttus_Proposal__ExpectedStartDate__c:	null,
		Apttus_Proposal__Generate__c:	null,
		Apttus_Proposal__Grand_Total__c:	null,
		Apttus_Proposal__Internal_Deadline__c:	null,
		Apttus_QPConfig__IsSystemGenerated__c:	null,
		Apttus_QPConfig__IsTaskPending__c:	null,
		Apttus_QPConfig__LocationId__c:	null,
		Apttus_Proposal__MakePrimary__c:	null,
		Apttus_Proposal__Net_Amount__c:	null,
		Apttus_Proposal__Opportunity__c:	null,
		Apttus_Proposal__Payment_Term__c:	null,
		Apttus_QPConfig__PaymentTermId__c:	null,
		Apttus_QPConfig__PODate__c:	null,
		Apttus_QPConfig__PONumber__c:	null,
		Apttus_Proposal__Present__c:	null,
		Apttus_Proposal__Presented_Date__c:	null,
		Apttus_Proposal__Preview__c:	null,
		Apttus_QPConfig__PriceListId__c:	null,
		Apttus_QPConfig__PricingDate__c:	null,
		Apttus_Proposal__Primary__c:	null,
		Apttus_Proposal__Primary_Contact__c:	null,
		Apttus_Proposal__Proposal_Approval_Date__c:	null,
		Apttus_Proposal__Proposal_Category__c:	null,
		Apttus_Proposal__Proposal_Expiration_Date__c:	null,
		Apttus_Proposal__Proposal_Name__c:	null,
		Apttus_QPConfig__ReadyForActivationDate__c:	null,
		Apttus_QPConfig__ReadyForBillingDate__c:	null,
		Apttus_QPConfig__ReadyForFulfillmentDate__c:	null,
		Apttus_QPConfig__ReadyForRevRecDate__c:	null,
		Apttus_Proposal__ReadyToGenerate__c:	null,
		Apttus_Proposal__ReadyToPresent__c:	null,
		Apttus_Proposal__Request_Approval__c:	null,
		Apttus_Proposal__RFP_Intake_Date__c:	null,
		Apttus_Proposal__RFP_Response_Due_Date__c:	null,
		Apttus_Proposal__RFP_Stage__c:	null,
		Apttus_Proposal__RFP_Value__c:	null,
		Apttus_Proposal__Risk_Factors__c:	null,
		Apttus_Proposal__Sales_Tax_Percent__c:	null,
		Apttus_Proposal__Sales_Tax_Amount__c:	null,
		Apttus_Proposal__SendProposal__c:	null,
		Apttus_Proposal__Shipping_Handling__c:	null,
		Apttus_QPConfig__ShipToAccountId__c:	null,
		Apttus_Proposal__Special_Terms__c:	null,
		Apttus_Proposal__Strategic_Importance__c:	null,
		Apttus_Proposal__SubmitForApproval__c:	null,
		Apttus_QPConfig__SyncAssetChangesToQuote__c:	null,
		Apttus_QPConfig__SyncWithOpportunity__c:	null,
		Apttus_Proposal__Valid_Until_Date__c:	null,
		Apttus_QPConfig__BillToAccountId__r: AccountFactory(true, false),
		Apttus_QPConfig__ShipToAccountId__r: AccountFactory(true, false)
	} as Quote;
}